// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQHpT0kJarjJhQJbjXcBb2mQG788WxVi4',
    appId: '1:969331341522:web:e3d82a0330d307c7fb150b',
    messagingSenderId: '969331341522',
    projectId: 'onlineapp-acfd1',
    authDomain: 'onlineapp-acfd1.firebaseapp.com',
    storageBucket: 'onlineapp-acfd1.appspot.com',
    measurementId: 'G-CQE3G2BFKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgWzqQjIg6lJRs1GMovTEcFBNUHkjVDyM',
    appId: '1:969331341522:android:f3d0cdceabdadbc4fb150b',
    messagingSenderId: '969331341522',
    projectId: 'onlineapp-acfd1',
    storageBucket: 'onlineapp-acfd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCapgHJhpOXhL7tp7HBoyDmGgLulXOoniI',
    appId: '1:969331341522:ios:f9c07c00c3d769c1fb150b',
    messagingSenderId: '969331341522',
    projectId: 'onlineapp-acfd1',
    storageBucket: 'onlineapp-acfd1.appspot.com',
    iosClientId: '969331341522-6ebg219d5tjt8uieop3rf00mg92ovn32.apps.googleusercontent.com',
    iosBundleId: 'com.blogspot.iamhumphrey.onlineapp',
  );
}
